version: 2
updates:
  # Weekly update configuration for Go Modules (go.mod)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Weekly update configuration for GitHub Actions (.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
